---

services:
  gluetun-pia-wireguard:
    image: pvd-nerd/gluetun-pia-wireguard
    container_name: gluetun-pia-wireguard
    restart: no
    environment:
      PIA_USER: piausername
      PIA_PASS: piapasssword
      PREFERRED_REGION: us_new_york_city
      VPN_PROTOCOL: wireguard
      CONFIG_OUTPUT_PATH: /app/config/wg0.conf
    volumes:
      - pia-config:/app/config

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      UPDATER_PERIOD: 24h
      TZ: Etc/UTC
      FIREWALL_OUTBOUND_SUBNETS: 172.16.0.0/12
    volumes:
      - gluetun-data:/gluetun
      - pia-config:/gluetun/wireguard:ro
    depends_on:
      gluetun-pia-wireguard:
        condition: service_completed_successfully

volumes:
  pia-config:
  gluetun-data: